app/app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from app import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('catalog/', include('goods.urls')),
    path('user/', include('users.urls')),
    path('cart/', include('carts.urls')),    
    path('orders/', include('orders.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += [path("__debug__/", include("debug_toolbar.urls"))]

app/users/urls.py
from django.urls import path
from .views import *

app_name = 'users'

urlpatterns = [
    path('login/', login, name='login'),
    path('registration/', registration, name='registration'),
    path('profile', profile, name='profile'),
    path('users-cart/', users_cart, name='users_cart'),
    path('logout/', logout, name='logout'),
]

app/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    image = models.ImageField(upload_to='users_images', blank=True, null=True, verbose_name='Аватар')
    phone_number = models.CharField(max_length=10, blank=True, null=True, verbose_name='Номер телефона')

    class Meta:
        db_table = 'user'
        verbose_name = 'Пользователя'
        verbose_name_plural = 'Пользователи'

    def __sts__(self):
        return f'{self.username} | {self.email} | {self.is_staff}'

app/users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from .models import User

class UserLoginForm(AuthenticationForm):
    username = forms.CharField()
    password = forms.CharField()

    class Meta:
        model = User
        fields = ('username', 'password')

class UserRegistrationForm(UserCreationForm):
    first_name = forms.CharField()
    last_name = forms.CharField()
    username = forms.CharField()
    email = forms.CharField()
    password1 = forms.CharField()
    password2 = forms.CharField()

    class Meta:
        model = User
        fields = (
            'first_name',
            'last_name',
            'username',
            'email',
            'password1',
            'password2',
        )
    
class UserProfileForm(UserChangeForm):
    image = forms.ImageField(required=False)
    first_name = forms.CharField()
    last_name = forms.CharField()
    username = forms.CharField()
    email = forms.CharField()
     
    class Meta:
        model = User
        fields = (
            'image',
            'first_name',
            'last_name',
            'username',
            'email'
        )

app/users/views.py
from django.shortcuts import redirect, render
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib import auth, messages
from django.db.models import Prefetch
from django.http import HttpResponseRedirect
from carts.models import Cart
from orders.models import Order, OrderItem
from .forms import UserLoginForm, UserRegistrationForm, UserProfileForm

def login(request):
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(username=username, password=password)
            
            session_key = request.session.session_key
            if user:
                auth.login(request, user)
                messages.success(request, f'{username}, Вы вошли в аккаунт')

                if session_key:
                    Cart.objects.filter(session_key=session_key).update(user=user)

                redirect_page = request.POST.get('next', None)
                if redirect_page and redirect_page != reverse('users:login'):
                    return HttpResponseRedirect(redirect_page)
            
                return HttpResponseRedirect(reverse('main:index'))
    else:
        form = UserLoginForm()

    context = {
        'title': 'O.Lib - Авторизация',
        'form': form,
    }
    return render(request, 'users/login.html', context)

def registration(request):
    if request.method == 'POST':
        form = UserRegistrationForm(data=request.POST)
        if form.is_valid():
            form.save()
            session_key = request.session.session_key
            user = form.instance
            auth.login(request, user)
            
            if session_key:
                Cart.objects.filter(session_key=session_key).update(user=user)
                    
            messages.success(request, f'{user.username}, Вы успешно зарегистрировались и вошли в аккаунт')
            return HttpResponseRedirect(reverse('main:index'))
    else:
        form = UserRegistrationForm()

    context = {
        'title': 'O.Lib - Регистрация',
        'form': form
    }
    return render(request, 'users/registration.html', context)

@login_required
def profile(request):
    if request.method == 'POST':
        form = UserProfileForm(data=request.POST, instance=request.user, files=request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, f'Ваши данные успешно обновлены')
            return HttpResponseRedirect(reverse('users:profile'))
    else:
        form = UserProfileForm(instance=request.user)
    orders = (
        Order.objects.filter(user=request.user).prefetch_related(
            Prefetch(
                'orderitem_set',
                queryset=OrderItem.objects.select_related('product'),
            )
        ).order_by('-id')
    )
    context = {
        'title': 'O.Lib - Мой профиль',
        'form': form,
        'orders': orders
    }
    return render(request, 'users/profile.html', context)

def users_cart(request):
    return render(request, 'users/users_cart.html')

@login_required
def logout(request):
    messages.success(request, f'{request.user.username}, Вы вышли из аккаунта')
    auth.logout(request)
    return redirect(reverse('main:index'))

app/templates/users/login.html
{% extends 'base.html' %}
{% load static %}

{% block title %}{{ title }}{% endblock %}

{% block modal_cart %}
    {% include 'includes/cart_button.html' %}
{% endblock %}

{% block content %}
    <!-- Контент на странице -->
    <div class="row">
        <div class="container mt-5">
            <div class="row justify-content-center">
                <div class="col-md-6 bg-white p-4 mb-4 mx-3 rounded custom-shadow">
                    <h2 class="text-center mb-4">Авторизация</h2>
                    
                    <form action="{% url 'users:login' %}" method="post">
                        {% csrf_token %}

                        {% if request.GET.next %}
                            <input type="hidden" name="next" value="{{ request.GET.next }}">
                        {% endif %}
                        
                        <div class="mb-3">
                            <label for="id_username" class="form-label">Имя пользователя</label>
                            <input type="text" name="username" 
                                    value="{% if form.username.value %}{{ form.username.value }}{% endif %}" 
                                    class="form-control" id="id_username" 
                                    placeholder="Введите ваше имя пользователя" 
                                    required>
                        </div>
                        <div class="mb-3">
                            <label for="id_password" class="form-label">Пароль</label>
                            <input type="password" name="password" 
                                    class="form-control" id="id_password" 
                                    placeholder="Введите ваш пароль" 
                                    required>
                        </div>

                        <!-- {% for i in form %}
                            <div class="mb-3">
                                <label for="{{ i.id_for_label }}" class="form-label">{{ i.label }}</label>
                                {{ i }}
                            </div>
                        {% endfor %} -->
                        
                        <!-- <div class="mb-3">
                            <label for="username" class="form-label">Имя пользователя</label>
                            <input type="text" class="form-control" id="username" placeholder="Введите ваше имя пользователя" required>
                        </div>
                        <div class="mb-3">
                            <label for="password" class="form-label">Пароль</label>
                            <input type="password" class="form-control" id="password" placeholder="Введите ваш пароль" required>
                        </div> -->
                        <button type="submit" class="btn btn-dark btn-block">Войти</button>
                    </form>
                    <div class="mt-3">
                        <a href="#">Забыли пароль?</a> | <a href="{% url 'users:registration' %}">Создать аккаунт</a>
                    </div>
                    <hr>
                    <div class="text-center">
                        <p>Или авторизуйтесь через:</p>
                        <a href="#" class="btn btn-dark">
                            <img class="mx-1" src="{% static 'deps/icons/google.svg' %}" alt="Catalog Icon" width="16" height="16">
                            Google
                        </a>
                        <a href="#" class="btn btn-dark">
                            <img class="mx-1" src="{% static 'deps/icons/facebook.svg' %}" alt="Catalog Icon" width="16" height="16">
                            Facebook
                        </a>
                        <a href="#" class="btn btn-dark">
                            <img class="mx-1" src="{% static 'deps/icons/github.svg' %}" alt="Catalog Icon" width="16" height="16">
                            GitHub
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

app/templates/users/registration.html
{% extends 'base.html' %}
{% load static %}

{% block title %}{{ title }}{% endblock %}

{% block modal_cart %}
    {% include 'includes/cart_button.html' %}
{% endblock %}

{% block content %}
    <!-- Контент на странице -->
    <div class="row">
        <div class="container mt-5">
            <div class="row justify-content-center">
                <div class="col-md-9 bg-white p-4 mb-5 mx-2 rounded custom-shadow">
                    <h2 class="text-center mb-4">Регистрация</h2>
                    <form action="{% url 'users:registration' %}" method="post">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-md-6 mb-3">
                                <label for="id_first_name" class="form-label">Имя*</label>
                                <input type="text" class="form-control" 
                                        id="id_first_name"
                                        value="{% if form.first_name.value %}{{ form.first_name.value }}{% endif %}"
                                        name="first_name"
                                        placeholder="Введите ваше имя" 
                                        required>
                                {% if form.first_name.errors %}
                                    <div class="alert alert-danger alert-dismissable fade show">
                                        {{ form.first_name.errors }}
                                    </div>
                                {% endif %}
                            </div>
                            <div class="col-md-6 mb-3">
                                <label for="id_last_name" class="form-label">Фамилия*</label>
                                <input type="text" class="form-control" 
                                        id="id_last_name"
                                        value="{% if form.last_name.value %}{{ form.last_name.value }}{% endif %}"
                                        name="last_name"
                                        placeholder="Введите вашу фамилию" 
                                        required>
                                {% if form.last_name.errors %}
                                    <div class="alert alert-danger alert-dismissable fade show">
                                        {{ form.last_name.errors }}
                                    </div>
                                {% endif %}
                            </div>
                            <div class="col-md-6 mb-3">
                                <label for="id_username" class="form-label">Имя пользователя*</label>
                                <input type="text" class="form-control" 
                                        id="id_username"
                                        value="{% if form.username.value %}{{ form.username.value }}{% endif %}"
                                        name="username"
                                        placeholder="Введите желаемое имя пользователя" 
                                        required>
                                {% if form.username.errors %}
                                    <div class="alert alert-danger alert-dismissable fade show">
                                        {{ form.username.errors }}
                                    </div>
                                {% endif %}
                            </div>
                            <div class="col-md-6 mb-3">
                                <label for="id_email" class="form-label">Email*</label>
                                <input type="email" class="form-control" 
                                        id="id_email"
                                        value="{% if form.email.value %}{{ form.email.value }}{% endif %}"
                                        name="email"
                                        placeholder="Введите ваш email" 
                                        required>
                                {% if form.email.errors %}
                                    <div class="alert alert-danger alert-dismissable fade show">
                                        {{ form.email.errors }}
                                    </div>
                                {% endif %}
                            </div>
                            <div class="col-md-6 mb-3">
                                <label for="id_password1" class="form-label">Пароль*</label>
                                <input type="password" class="form-control" 
                                        id="id_password1"
                                        value="{% if form.password1.value %}{{ form.password1.value }}{% endif %}"
                                        name="password1"
                                        placeholder="Введите пароль" 
                                        required>
                                {% if form.password1.errors %}
                                    <div class="alert alert-danger alert-dismissable fade show">
                                        {{ form.password1.errors }}
                                    </div>
                                {% endif %}
                            </div>
                            <div class="col-md-6 mb-3">
                                <label for="id_password2" class="form-label">Подтверждение пароля*</label>
                                <input type="password" class="form-control" 
                                        id="id_password2"
                                        value="{% if form.password2.value %}{{ form.password2.value }}{% endif %}"
                                        name="password2"
                                        placeholder="Подтвердите пароль" 
                                        required>
                                {% if form.password2.errors %}
                                    <div class="alert alert-danger alert-dismissable fade show">
                                        {{ form.password2.errors }}
                                    </div>
                                {% endif %}
                            </div>
                        </div>
                        <button type="submit"
                            class="btn btn-dark btn-block">Зарегистрироваться</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

app/templates/users/users_cart.html
{% extends 'base.html' %}
{% load static %}
{% load carts_tags %}

{% user_carts request as carts %}

{% block content %}
{% user_carts request as carts %}
<!-- Контент на странице -->
<div class="row">
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                <h3 class="text-center mb-4">Корзина</h3>
                <div class="container" id="cart-items-container">
                    <!-- Разметка корзины -->
                    {% include 'carts/included_cart.html' %}
                    <!-- Закончилась разметка корзины -->
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}