app/app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from app import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('catalog/', include('goods.urls')),
    path('user/', include('users.urls')),
    path('cart/', include('carts.urls')),    
    path('orders/', include('orders.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += [path("__debug__/", include("debug_toolbar.urls"))]

app/carts/urls.py
from django.urls import path
from .views import *

app_name = 'carts'

urlpatterns = [
    path('cart_add/', cart_add, name='cart_add'),
    path('cart_change/', cart_change, name='cart_change'),
    path('cart_remove/', cart_remove, name='cart_remove'),
    
]

app/goods/urls.py
from django.urls import path
from .views import *

app_name = 'catalog'

urlpatterns = [
    path('search/', catalog, name='search'),
    path('<slug:category_slug>/', catalog, name='catalog'),
    path('product/<slug:slug>/', product, name='product'),
]

app/orders/urls.py
from django.urls import path
from .views import *

app_name = 'orders'

urlpatterns = [
    path('create_order/', create_order, name='create_order'),
]

app/carts/models.py
from django.db import models
from users.models import User
from goods.models import Products

class CartQueryset(models.QuerySet):
    def total_price(self):
        return sum(cart.products_price() for cart in self)

    def total_quantity(self):
        if self:
            return sum(cart.quantity for cart in self)
        return 0

class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True, verbose_name='Пользователь')
    product = models.ForeignKey(Products, on_delete=models.CASCADE, verbose_name='Продукт')
    quantity = models.PositiveSmallIntegerField(default=0, verbose_name='Количество')
    created_timestamp = models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')

    session_key = models.CharField(max_length=32, null=True, verbose_name='Сессионный ключ')
    objects = CartQueryset.as_manager()

    class Meta:
        ordering = ['id']
        db_table = 'cart'
        verbose_name = 'Корзина'
        verbose_name_plural = 'Корзина'

    def products_price(self):
        return round(self.product.sell_price() * self.quantity, 2)

    def __str__(self):
        if not self.user:
            user = 'Anonimous'
        else:
            user = self.user.username

        return f'Корзина {user} | Товар {self.product.name} | Количество {self.quantity} | Сессия {self.session_key}'

app/carts/views.py
from django.shortcuts import redirect
from django.template.loader import render_to_string
from django.http import JsonResponse
from goods.models import Products
from carts.utils import get_user_carts
from .models import Cart

def cart_add(request):
    product_id = request.POST.get('product_id')
    product = Products.objects.get(id=product_id)

    if request.user.is_authenticated:
        carts = Cart.objects.filter(user=request.user, product=product)
        if carts.exists():
            cart = carts.first()
            if cart:
                cart.quantity += 1
                cart.save()
        else:
            Cart.objects.create(user=request.user, product=product, quantity=1)
    else:
        carts = Cart.objects.filter(
            session_key=request.session.session_key, product=product
        )
    
        if carts.exists():
            cart = carts.first()
            if cart:
                cart.quantity += 1
                cart.save()
        else:
            Cart.objects.create(
                session_key=request.session.session_key, product=product, quantity=1
            )
    user_cart = get_user_carts(request)
    cart_items_html = render_to_string(
        "carts/included_cart.html", {"carts": user_cart}, request=request)

    response_data = {
        "message": "Товар добавлен в корзину",
        "cart_items_html": cart_items_html,
    }

    return JsonResponse(response_data)

def cart_change(request):
    cart_id = request.POST.get('cart_id')
    quantity = request.POST.get('quantity')
    
    cart = Cart.objects.get(id=cart_id)
    cart.quantity = quantity
    cart.save()

    updated_quantity = cart.quantity
    user_cart = get_user_carts(request)
    
    cart_items_html = render_to_string(
        'carts/included_cart.html', {'carts': user_cart}, request=request)

    response_data = {
        'message': 'Количество изменено',
        'cart_items_html': cart_items_html,
        'quantity': updated_quantity,
    }

    return JsonResponse(response_data)

def cart_remove(request):
    cart_id = request.POST.get('cart_id')
    cart = Cart.objects.get(id=cart_id)
    quantity = cart.quantity
    cart.delete()

    user_cart = get_user_carts(request)
    cart_items_html = render_to_string(
        'carts/included_cart.html', {'carts': user_cart}, request=request)

    response_data = {
        'message': 'Товар удалён',
        'cart_items_html': cart_items_html,
        'quantity_deleted': quantity,
    }

    return JsonResponse(response_data)

app/templates/carts/cart.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../deps/css/bootstrap/bootstrap.min.css">
    <link rel="stylesheet" href="../deps/css/my_css.css">
    <link rel="apple-touch-icon" sizes="180x180" href="../deps/favicon/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="../deps/favicon/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="../deps/favicon/favicon-16x16.png">
    <link rel="manifest" href="../deps/favicon/site.webmanifest">
    <title>Корзина</title>
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
            <div class="container">
                <a class="navbar-brand" href="../index.html">Home</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item dropdown ">
                            <a class="nav-link dropdown-toggle text-white" href="#" role="button"
                                data-bs-toggle="dropdown" aria-expanded="false">
                                Информация
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item  text-white" href="#">Доставка и оплата</a></li>
                                <li><a class="dropdown-item  text-white" href="#">Контактная информация</a></li>
                                <li><a class="dropdown-item  text-white" href="#">Про нас</a></li>
                            </ul>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link  text-white" href="../users/cart.html">Корзина</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link  text-white" href="../users/login.html">Войти</a>
                        </li>
                        <li class="nav-item dropdown ">
                            <a class="nav-link dropdown-toggle text-white" href="#" role="button"
                                data-bs-toggle="dropdown" aria-expanded="false">
                                Мой профиль
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item  text-white" href="../users/cart.html">Корзина</a></li>
                                <li><a class="dropdown-item  text-white" href="../users/profile.html">Личный кабинет</a>
                                </li>
                                <li><a class="dropdown-item  text-white" href="#">Админ панель</a></li>
                                <li>
                                    <hr class="dropdown-divider">
                                </li>
                                <li><a class="dropdown-item  text-white" href="#">Выйти</a></li>
                            </ul>
                        </li>
                    </ul>
                    <form class="d-flex" role="search">
                        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                        <button class="btn btn-outline-success text-white" type="submit">Поиск</button>
                    </form>
                </div>
            </div>
        </nav>
    </header>
    <section>
        <div class="container">
            <!-- Каталог и корзина с фиксированным расположением на странице -->
            <div class="row mt-1 position-fixed z-3">
                <!-- Каталог -->
                <div class="dropdown mb-2">
                    <button class="btn btn-secondary dropdown-toggle btn-dark" type="button" data-bs-toggle="dropdown"
                        aria-expanded="false">
                        Каталог
                        <img class="mx-1" src="../deps/icons/grid-fill.svg" alt="Catalog Icon" width="16"
                            height="16">
                    </button>
                    <ul class="dropdown-menu bg-dark" data-bs-theme="dark">
                        <li><a class="dropdown-item text-white" href="../goods/catalog.html">Все товары</a></li>
                        <li><a class="dropdown-item text-white" href="../goods/catalog.html">Кухня</a></li>
                        <li><a class="dropdown-item text-white" href="../goods/catalog.html">Спальня</a></li>
                        <li><a class="dropdown-item text-white" href="../goods/catalog.html">Гостинная</a></li>
                        <li><a class="dropdown-item text-white" href="../goods/catalog.html">Офис</a></li>
                        <li><a class="dropdown-item text-white" href="../goods/catalog.html">Фурнитура</a></li>
                        <li><a class="dropdown-item text-white" href="../goods/catalog.html">Декор</a></li>
                    </ul>
                </div>
            </div>
        </div>
        <!-- Контент -->
        <div class="container">
            <div class="row mt-1">
                <div class="col-lg-2">
                    <!-- Пустой блок на усмотрение -->
                </div>
                <div class="col-lg-10">
                    <!-- Контент на странице -->
                    <div class="row">
                        <div class="container mt-5">
                            <div class="row justify-content-center">
                                <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                                    <h3 class="text-center mb-4">Корзина</h3>
                                    <div class="container" id="cart-items-container">
                                        <!-- Разметка корзины -->
                                        <div class="card mb-3 text-bg-light shadow-lg">
                                            <div class="card-header">
                                                <h5 class="card-title">Товар</h5>
                                            </div>
                                            <ul class="list-group list-group-flush">
                                                <li class="list-group-item">
                                                    <div class="row text-center">
                                                        <div class="col p-0">
                                                            <div class="input-group">
                                                                <span class="input-group-btn">
                                                                    <button type="button" class="btn btn-dark btn-sm decrement"
                                                                        data-cart-id="" data-cart-change-url="">-</button>
                                                                </span>
                                                                <input type="text" class="form-control number" value="1"
                                                                    readonly>
                                                                <span class="input-group-btn">
                                                                    <button type="button" class="btn btn-dark btn-sm increment"
                                                                        data-cart-id="" data-cart-change-url="">+</button>
                                                                </span>
                                                            </div>
                                                        </div>
                                                        <div class="col p-0">
                                                            <p>x 100.00 = </p>
                                                        </div>
                                                        <div class="col p-0"><strong>100.00 $</strong></div>
                                                        <div class="col p-0">
                                                            <a href="#" class="remove-from-cart" data-cart-id="">
                                                                <img class="mx-1" src="../deps/icons/trash3-fill.svg"
                                                                    alt="Catalog Icon" width="16" height="16">
                                                            </a>
                                                        </div>
                                                    </div>
                                                </li>
                                            </ul>
                                        </div>
                                        <div class="card mb-3 shadow-lg">
                                            <div class="card-footer">
                                                <p class="float-left">Итого <strong>1</strong> товар(а) на сумму</p>
                                                <h4 class="float-left"><strong>100.00 $</strong></h4>
                                            </div>
                                        </div>
                                        <!-- Закончилась разметка корзины -->
                                    </div>
                                    <a class="btn btn-dark" href="../orders/create_order.html">
                                        Оформить заказ
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <script src="../deps/js/jquery/jquery-3.7.0.min.js"></script>
    <script src="../deps/js/jquery-events.js"></script>
    <script src="../deps/js/jquery-ajax.js"></script>
    <script src="../deps/js/bootstrap/bootstrap.bundle.min.js"></script>
</body>

</html>

app/templates/carts/included_cart.html
{% load static %}


<div class="card mb-3 text-bg-light shadow-lg">
    {% for cart in carts %}
        <div class="card-header">
            <a class="link-underline link-underline-opacity-0" href="{% url 'catalog:product' cart.product.slug %}">
                <h5 class="card-title">{{ cart.product.name }}</h5>
            </a>
        </div>
        <ul class="list-group list-group-flush">
            <li class="list-group-item">
                <div class="row text-center">
                    <div class="col p-0">
                        <div class="input-group">
                            <span class="input-group-btn">
                                <button type="button" class="btn btn-dark btn-sm decrement"
                                    data-cart-id="{{ cart.id }}" 
                                    data-cart-change-url="{% url 'carts:cart_change' %}">
                                    {% csrf_token %}
                                    -</button>
                            </span>
                            <input type="text" class="form-control number" value="{{ cart.quantity }}"
                                readonly>
                            <span class="input-group-btn">
                                <button type="button" class="btn btn-dark btn-sm increment"
                                    data-cart-id="{{ cart.id }}" 
                                    data-cart-change-url="{% url 'carts:cart_change' %}">
                                    {% csrf_token %}
                                    +</button>
                            </span>
                        </div>
                    </div>
                    <div class="col p-0">
                        <p>x {{ cart.product.sell_price }} = </p>
                    </div>
                    <div class="col p-0"><strong>{{ cart.products_price }} руб.</strong></div>
                    <div class="col p-0">
                        <a href="{% url 'carts:cart_remove' %}" class="remove-from-cart" 
                            data-cart-id="{{ cart.id }}">
                            {% csrf_token %}
                            <img class="mx-1" src="{% static 'deps/icons/trash3-fill.svg' %}"
                                alt="Catalog Icon" width="16" height="16">
                        </a>
                    </div>
                </div>
            </li>
        </ul>
    {% endfor %}
</div>
<div class="card mb-3 shadow-lg">
    <div class="card-footer">
        <p class="float-left">Итого <strong>{{ carts.total_quantity }}</strong> товар(а) на сумму</p>
        <h4 class="float-left"><strong>{{ carts.total_price }} руб.</strong></h4>
    </div>
</div>


{% if carts and not order %}
    <a class="btn btn-dark" href="{% url 'orders:create_order' %}">
        Оформить заказ
    </a>
{% endif %}